# Generated by Django 6.0.3 on 2026-03-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tempo_leitura', models.IntegerField()),
                ('data_postagem', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=100)),
                ('destaque', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
